### ISSUE TITLE
加载问题

### ISSUE THREAD

**Issue by yuanbaoyang** [komalsdagde/document_viewer#4]
加载某些doc和docx文件会报错
flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Could not find End of Central Directory Record
    #0      ZipDirectory._findSignature (package:archive/src/zip/zip_directory.dart:149:5)
    #1      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:28:20)
    #2      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:24:30)
    #3      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:16:12)
    #4      docxToText (package:docx_to_text/src/docx_to_text_src.dart:16:32)
    #5      _DocumentViewerState.readFromDocxFile (package:document_viewer/src/document_viewer.dart:136:15)
    <asynchronous suspension>

另外加载txt好像没效果？也没任何报错页面就是空白  

下面是我的加载代码 版本0.0.2-2和0.0.1都试了
![image](https://github.com/komalsdagde/document_viewer/assets/129161361/1bcdc9ae-90a5-40ee-9a94-9c2bf995f4ae)

**Comment by Appstute-Prerna** [comment]
Your both files have same path "localfile" and "file". Please copy from diffrent path if you want to write to different path. Also avoid using string name as "Path". Hope it helps. Thanks

**Comment by yuanbaoyang** [comment]
> 您的两个文件具有相同的路径“localfile”和“file”。如果要写入不同的路径，请从不同的路径复制。还要避免使用字符串名称作为“路径”。希望能帮助到你。谢谢

另外加载txt好像没效果？也没任何报错页面就是空白？

**Comment by Appstute-Prerna** [comment]
> > 您的两个文件具有相同的路径“localfile”和“file”。如果要写入不同的路径，请从不同的路径复制。还要避免使用字符串名称作为“路径”。希望能帮助到你。谢谢
> 
> 另外加载txt好像没效果？也没任何报错页面就是空白？

May be your file i.e .docx file may have images into it. So unable to read docx to text. Developer is still working on images in docx format.

**Comment by yuanbaoyang** [comment]
> > > 您的两个文件具有相同的路径“localfile”和“file”。如果要写入不同的路径，请从不同的路径复制。还要避免使用字符串名称作为“路径”。希望能对您有所帮助。谢谢
> > 
> > 
> > 另外加载txt希望没效果？也没有报错页面就是空白？
> 
> 可能是您的文件（即 .docx 文件）中可能包含图像。因此无法将 docx 读取为文本。开发人员仍在处理 docx 格式的图像。

我的意思是直接加载txt文件失败 不是.docx文件是.txt文件 我看你源码中
![image](https://github.com/komalsdagde/document_viewer/assets/129161361/530ce85d-5690-4e4d-b53b-229d607583da)
是否少调用了setState(() {});方法？

**Comment by komalsdagde** [comment]
I have made those changes in the latest release you can check that. I think it will resolve your issue.

**Comment by yuanbaoyang** [comment]
> 我已经在最新版本中进行了这些更改，您可以检查一下。我认为这会解决你的问题。

![image](https://github.com/komalsdagde/document_viewer/assets/129161361/f35fa9b8-f1ad-482e-a595-06a32fb7f573)
最新^0.0.2-3中 还是有些文件加载错误 .doc报错上面截图  有些.txt也加载不出来但是也没有报错

**Comment by Appstute-Prerna** [comment]
I could see your filepath went wrong. Please copy a file where you can access through like save the file in getAppicationStorageDirecory() or getExternalStorageDirectory() by creating file name. And use the same path in DocViewer

 For path ::   Directory dir = await getApplicationDocumentsDirectory();
                    File f = new File(dir.path + "/filename.doc");
                    
 Usage ::   Container(
                color: Colors.white,
                child: doc.DocumentViewer(
                    filePath: f.path),
              );

**Comment by yuanbaoyang** [comment]
> 

按你的方式试了一下还是不行 确实加载不出来 路径没问题  而且我不是所有文件都加载不出来 就是个别文件 
![image](https://github.com/komalsdagde/document_viewer/assets/129161361/5b2b4f61-779e-4dd9-a87d-51b0cec9e67a)
![image](https://github.com/komalsdagde/document_viewer/assets/129161361/d23451d3-20c6-44c0-8eaa-ef3cbb5612b9)
![image](https://github.com/komalsdagde/document_viewer/assets/129161361/c9287cd5-8ef6-4dd9-907c-26f3a2e3f33d)

**Comment by Appstute-Prerna** [comment]
The file is either corrupt, the file download is incomplete, or it's a multi-part archive file and the other components are not found, or the zip file is not actually a zip. I guess you are working with zip files. Check if the file is downloaded correctly. See if you can open the file from the external path you selected in files.

**Comment by yuanbaoyang** [comment]
> 文件已损坏、文件下载不完整、或者它是由多部分组成的存档文件且未找到其他组件，或者 zip 文件实际上不是 zip。我猜你正在使用 zip 文件。检查文件是否正确下载。查看是否可以从文件中选择的外部路径打开该文件。

选择的文件外部可以打开 或者我可以把文件发你测试一下

**Comment by Appstute-Prerna** [comment]
That would help thanks

**Comment by yuanbaoyang** [comment]
> 那会有所帮助谢谢

但是这里发不了文件 哪里能上传文件吗

**Comment by Appstute-Prerna** [comment]
you can send it to prernapatil0905@gmail.com

**Comment by yuanbaoyang** [comment]
> 您可以将其发送至[prernapatil0905@gmail.com](mailto:prernapatil0905@gmail.com)

已发送两个文件到你谷歌邮箱 注意查收

**Comment by komalsdagde** [comment]
Currently package supports the English language only. we will try to provide other language support in future versions.

**Comment by yuanbaoyang** [comment]
> 目前软件包仅支持英语。我们将尝试在未来的版本中提供其他语言的支持。

什么意思？是指文件里边的内容只支持英语吗？

**Comment by komalsdagde** [comment]
Yes, currently it supports English only.

**Comment by yuanbaoyang** [comment]
> 是的，目前仅支持英语。

为什么我有的文件可以打开 有中文不过也有英文 你的意思是内容里边全部是中文就不行吗？

**Comment by komalsdagde** [comment]
The content we are supposed to read i.e. .doc and .txt will not show in Chinese. If it is PDF then maybe the plugin supports other languages

**Comment by yuanbaoyang** [comment]
> 

好的  希望能尽早更新支持中文  谢谢

**Comment by komalsdagde** [comment]
Yes sure

**Comment by komalsdagde** [comment]
Yes sure
